let mock2 = [{"id":1,"first_name":"Carolee","last_name":"Barkway","bio":"deploy proactive users","company":"Little-Toy","avg_score":-167},
{"id":2,"first_name":"Edyth","last_name":"Pimlott","bio":"unleash ubiquitous schemas","company":"Kihn, Johns and Heller","avg_score":36},
{"id":3,"first_name":"Gertie","last_name":"Drinkel","bio":"extend value-added e-markets","company":"Stracke, Ferry and West","avg_score":85},
{"id":4,"first_name":"Paul","last_name":"McNair","bio":"extend sticky markets","company":"Predovic, Hilll and Carroll","avg_score":230},
{"id":5,"first_name":"Rafael","last_name":"Lai","bio":"synergize seamless paradigms","company":"Huels-Muller","avg_score":97},
{"id":6,"first_name":"Sherline","last_name":"Bellow","bio":"drive out-of-the-box action-items","company":"Senger-Boyer","avg_score":-78},
{"id":7,"first_name":"Christoforo","last_name":"Gerler","bio":"aggregate holistic convergence","company":"Herzog-Satterfield","avg_score":-13},
{"id":8,"first_name":"York","last_name":"Swynley","bio":"incentivize web-enabled models","company":"Ernser-Thiel","avg_score":300},
{"id":9,"first_name":"Tybie","last_name":"Bicker","bio":"seize frictionless e-tailers","company":"Haley and Sons","avg_score":-290},
{"id":10,"first_name":"Claire","last_name":"Allardyce","bio":"strategize ubiquitous models","company":"Hagenes LLC","avg_score":14},
{"id":11,"first_name":"Nalani","last_name":"Eagle","bio":"redefine back-end relationships","company":"Gorczany, Schroeder and Roberts","avg_score":-5},
{"id":12,"first_name":"Daryl","last_name":"Likly","bio":"embrace extensible functionalities","company":"Schmeler-Green","avg_score":-317},
{"id":13,"first_name":"Guillaume","last_name":"Diplock","bio":"benchmark bricks-and-clicks channels","company":"Cruickshank Group","avg_score":-39},
{"id":14,"first_name":"Lilly","last_name":"Gilman","bio":"redefine efficient communities","company":"Koepp, Kassulke and Hickle","avg_score":79},
{"id":15,"first_name":"Tera","last_name":"Welham","bio":"brand rich deliverables","company":"Schimmel and Sons","avg_score":-100},
{"id":16,"first_name":"Drusy","last_name":"Morpeth","bio":"integrate strategic niches","company":"Russel LLC","avg_score":71},
{"id":17,"first_name":"Nathaniel","last_name":"Ivashchenko","bio":"leverage interactive experiences","company":"Hansen-Goodwin","avg_score":235},
{"id":18,"first_name":"Cynthea","last_name":"Sermin","bio":"reintermediate compelling schemas","company":"Ondricka LLC","avg_score":-40},
{"id":19,"first_name":"Jefferson","last_name":"Humphris","bio":"mesh plug-and-play communities","company":"O'Keefe, Erdman and Flatley","avg_score":-66},
{"id":20,"first_name":"Mariya","last_name":"Hincham","bio":"monetize innovative vortals","company":"Schultz Inc","avg_score":29},
{"id":21,"first_name":"Albertine","last_name":"Eisold","bio":"architect e-business users","company":"Schoen, Mohr and Friesen","avg_score":39},
{"id":22,"first_name":"Odey","last_name":"Stickles","bio":"generate 24/7 bandwidth","company":"Block, Gorczany and Lakin","avg_score":-81},
{"id":23,"first_name":"Tressa","last_name":"Malenoir","bio":"drive e-business solutions","company":"Howell-Keeling","avg_score":34},
{"id":24,"first_name":"Ches","last_name":"Buret","bio":"seize bleeding-edge e-tailers","company":"Ortiz-Wunsch","avg_score":93},
{"id":25,"first_name":"Oswell","last_name":"McHan","bio":"iterate B2B infrastructures","company":"Steuber, Sporer and Kovacek","avg_score":54},
{"id":26,"first_name":"Shelby","last_name":"Moulsdall","bio":"deploy innovative eyeballs","company":"Corkery-Sporer","avg_score":-70},
{"id":27,"first_name":"Marcella","last_name":"Bartoli","bio":"orchestrate intuitive infomediaries","company":"Lesch Inc","avg_score":97},
{"id":28,"first_name":"Clint","last_name":"Garrals","bio":"orchestrate cutting-edge platforms","company":"Bahringer-Heidenreich","avg_score":81},
{"id":29,"first_name":"Cordy","last_name":"Stickler","bio":"target cross-platform schemas","company":"Schmeler and Sons","avg_score":86},
{"id":30,"first_name":"Hercule","last_name":"Jennaway","bio":"deploy virtual vortals","company":"Emmerich, Cole and Bradtke","avg_score":49},
{"id":31,"first_name":"Gertrud","last_name":"Aleksidze","bio":"revolutionize one-to-one relationships","company":"Ruecker, Erdman and Farrell","avg_score":-20},
{"id":32,"first_name":"Trude","last_name":"Maylam","bio":"productize dynamic initiatives","company":"Corwin-O'Reilly","avg_score":21},
{"id":33,"first_name":"Viki","last_name":"Davidovits","bio":"brand virtual solutions","company":"Langosh-Reichel","avg_score":-90},
{"id":34,"first_name":"Hersh","last_name":"Bolesma","bio":"disintermediate integrated applications","company":"DuBuque-Hickle","avg_score":86},
{"id":35,"first_name":"Pincas","last_name":"Espin","bio":"deploy efficient networks","company":"Stoltenberg, Brown and Bahringer","avg_score":-35},
{"id":36,"first_name":"Courtney","last_name":"Skene","bio":"drive e-business e-services","company":"Vandervort LLC","avg_score":52},
{"id":37,"first_name":"Ruthi","last_name":"Van T'Hoog","bio":"target revolutionary e-commerce","company":"Considine-Hudson","avg_score":-36},
{"id":38,"first_name":"Issi","last_name":"Kearley","bio":"maximize wireless technologies","company":"Grimes-Dickinson","avg_score":27},
{"id":39,"first_name":"Priscilla","last_name":"Yen","bio":"target interesting technologies","company":"Lindgren, Anderson and Bashirian","avg_score":97},
{"id":40,"first_name":"Leyster","last_name":"Buchanon","bio":"repurpose mission-critical initiatives","company":"Weber-Kertzmann","avg_score":-54},
{"id":41,"first_name":"Xerxes","last_name":"Speares","bio":"recontextualize global web services","company":"Greenfelder Inc","avg_score":-68},
{"id":42,"first_name":"Meryl","last_name":"Jurczik","bio":"streamline cutting-edge paradigms","company":"Bechtelar and Sons","avg_score":78},
{"id":43,"first_name":"Beverie","last_name":"Shovelin","bio":"incubate plug-and-play models","company":"Ebert, Lind and Pfannerstill","avg_score":-93},
{"id":44,"first_name":"Aura","last_name":"Furlow","bio":"extend cross-media interfaces","company":"Morar, Block and Satterfield","avg_score":17},
{"id":45,"first_name":"Gherardo","last_name":"Huckin","bio":"deliver plug-and-play content","company":"Russel-Pfeffer","avg_score":-69},
{"id":46,"first_name":"Ginelle","last_name":"Janous","bio":"facilitate 24/365 web-readiness","company":"Windler-Fritsch","avg_score":-19},
{"id":47,"first_name":"Billy","last_name":"Fletcher","bio":"enhance proactive users","company":"Casper Group","avg_score":41},
{"id":48,"first_name":"Carina","last_name":"Fairtlough","bio":"expedite innovative architectures","company":"Rath, Stracke and Little","avg_score":-301},
{"id":49,"first_name":"Aldric","last_name":"Bareford","bio":"innovate rich systems","company":"Heidenreich-Cruickshank","avg_score":-14},
{"id":50,"first_name":"Shanda","last_name":"Brasse","bio":"incentivize leading-edge solutions","company":"Harris, Schowalter and Corkery","avg_score":10}]
export default mock2;